lua/blink/cmp/config.lua, lua/blink/cmp/windows/autocomplete.lua, lua/blink/cmp/windows/documentation.lua
- Added `winhighlight` support to enable user-defined highlight customization for both autocomplete and documentation windows.
- Enhances user control over window appearance for a more personalized interface.
=> feat: introduce customizable winhighlight for autocomplete and documentation windows

README.md, lua/blink/cmp/config.lua
This PR fixes the incorrect default keymap for `select_next` and `select_prev`.
=> fix: use correct prev/next keymap for k and j

rust-toolchain.toml
This allows a `cargo build --release` and `rust-analyzer` to work without extra flags.
=> Add rust-toolchain.toml to require nightly.

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/windows/autocomplete.lua
resolves #8. 
calling `select_prev` at the beginning of the completion list will now cycle to the end.
calling `select_next` at the end of the completion list will now cycle back to the beginning.
it may make sense to make this config-driven, let me know what you'd prefer!
=> feat: cycle completions

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/fuzzy/download.lua
This adds a new `downloader` config table which allows:
1. Enabling or disabling the dll downloader
2. Explicitly specifying the version to download
This is useful if I want to track master (and get the latest lua changes) without needing to run `cargo build --release`.
=> Add config to explicitly specify the dll version

README.md, lua/blink/cmp/config.lua
https://github.com/Saghen/blink.cmp/pull/23#issuecomment-2399876619 nvim-cmp uses `ctrl-n` and `ctrl-p` by default for choosing items in a completion windows. So does vanilla Neovim and Emacs and pretty much every terminal application I know of. `ctrl-j` and `ctrl-k` are unidiomatic.
=> fix: use correct prev/next keymap

README.md
Musl libc doesnt support dynamic linking unless a specific RUSTFLAG is provided, i added this flag in the README:
> -- OR build from source, requires nightly: https://rust-lang.github.io/rustup/concepts/channels.html#working-with-nightly-rust
-- build = 'cargo build --release',
-- On musl libc based systems you need to add this flag
-- build = 'RUSTFLAGS="-C target-feature=-crt-static" cargo build --release',
=> doc: add musl libc support

lua/blink/cmp/config.lua
Hello @Saghen 
First of all, congrats on the plugin! My initial impression has been great. 
This patch fixes a somewhat selfish issue of mine. I prefer to use the `config` function to run configure plugins over `opts` just for a bit more flexibility and the added benefit of completions for option names. 
However, in the current `blink.cmp.Config` class, all fields are required. This results in a bit of an unsightly warning:
With this fix, the options aren't required anymore (which reflects reality) and the warning is no longer present when configuring via the `config` option in lazy.
Let me know if you have any questions!
=> fix(config): make blink lua config fields optional

lua/blink/cmp/trigger/completion.lua
As a nvim-cmp user, I was used to close the completion window with ctrl+c (it's kind of muscle memory at this point).
So I wanted to add the ability to blink.cmp too. Before this PR, the completion would not be closed as C-c does not trigger the InsertLeave autocommand in Vim/Nvim.
Currently, it looks like this:
Notice that my cursor is on line 13, outside of the completion window after I pressed ctrl+c.
For reference, nvim-cmp does something similar here:
https://github.com/hrsh7th/nvim-cmp/blob/ae644feb7b67bf1ce4260c231d1d4300b19c6f30/plugin/cmp.lua#L43-L54
=> fix: close completion window on ctrl+c in insert mode

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/windows/autocomplete.lua, lua/blink/cmp/windows/lib/init.lua, lua/blink/cmp/windows/lib/render.lua
Before
After
I have a custom `windows.autocomplete.draw` function:
```lua
draw = function(ctx)
return {
{
ctx.item.label,
ctx.kind == "Snippet" and "~" or nil,
fill = true,
hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
},
" ",
{ ctx.kind, hl_group = "BlinkCmpKind" .. ctx.kind },
}
end
```
* I've removed `windows.autocomplete.min_width` and `windows.autocomplete.max_width` since it's way easier to maintain the alignment without those, but in compensation, `max_width` component option was added:
```lua
draw = function(ctx)
return {
{
ctx.item.label,
ctx.kind == "Snippet" and "~" or nil,
fill = true,
max_width = 5,
hl_group = ctx.deprecated and "BlinkCmpLabelDeprecated" or "BlinkCmpLabel",
},
" ",
{ ctx.kind, hl_group = "BlinkCmpKind" .. ctx.kind },
}
end
``` …
=> fix!: autocompletion window components alignment

lua/blink/cmp/keymap.lua
Given the following config:
```lua
require("blink.cmp").setup({
keymap = {
select_prev = { "<S-Tab>" },
},
})
vim.keymap.set("i", "<S-Tab>", "<C-o>A")
```
Pressing `<S-Tab>` in insert mode when the Blink window is not visible creates an error:
```
E5108: Error executing lua: Vim:E15: Invalid expression: "^OA"
```
The issue is that `nvim_eval` is unconditionally called on `mapping.rhs`, so this PR fixes the logic to only evaluate the result of `<expr>` mappings. 
I also fixed a bug in the `if mapping` conditions, which are a little different in nvim-cmp because [these fields are converted into boolean values](https://github.com/hrsh7th/nvim-cmp/blob/ae644feb7b67bf1ce4260c231d1d4300b19c6f30/lua/cmp/utils/keymap.lua#L209).
As you noted in a comment, handling fallback keymaps correctly in all …
=> fix: correctly handle non-blink keymaps with string rhs

lua/blink/cmp/windows/documentation.lua
Stylize the documentation window
Before:
After:
=> feat: add detail to documentation window

README.md, lua/blink/cmp/fuzzy/init.lua, lua/blink/cmp/init.lua, lua/blink/cmp/sources/buffer.lua, lua/blink/cmp/trigger/completion.lua, lua/blink/cmp/trigger/signature.lua, lua/blink/cmp/windows/autocomplete.lua
This allows for `copilot.lua` (and others I'm sure) ghost text to be hidden when the completion menu is shown:
```lua
-- Remove Copilot ghost text when the cmp menu is opened.
ev.on_load("blink.cmp", function()
vim.schedule(function()
local cmp = require("blink.cmp")
cmp.on_show(function()
require("copilot.suggestion").dismiss()
vim.api.nvim_buf_set_var(0, "copilot_suggestion_hidden", true)
end)
cmp.on_hide(function()
vim.api.nvim_buf_set_var(0, "copilot_suggestion_hidden", false)
end)
end)
end)
```
I'm not sure of the best place to document this at the moment.
Fix some typos and syntax issue in the README as well.
=> Add basic event trigger API

lua/blink/cmp/windows/lib/render.lua
The current implementation only checks the min_width for one component, this PR does it for each component and modifies the length of the first (`fill` if found) component
=> fix: respect autocomplete min_width

lua/blink/cmp/windows/lib/render.lua
Oops, this should handle properly if the first component and the second one have `fill = true`
=> fix: don't initialize first_fill with 1

lua/blink/cmp/sources/snippets/utils.lua
When formating documentation of snippets, we treat the description field of a snippet item as string by default but it could a list of string sometimes(see [snippets for shell in friendly-snippets](https://github.com/rafamadriz/friendly-snippets/blob/de8fce94985873666bd9712ea3e49ee17aadb1ed/snippets/shell/shell.json#L62) ) which might cause a concatenation failure.
So here is a tiny fix by joining the description list if it is a list when loading snippets, so now it could be shown and looks like this:
Closes https://github.com/Saghen/blink.cmp/issues/91
=> fix: documentation of snippet cannot be shown when description is list

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/sources/lib/async.lua, lua/blink/cmp/sources/lib/context.lua, lua/blink/cmp/sources/lib/init.lua, lua/blink/cmp/sources/lib/provider.lua, lua/blink/cmp/sources/lib/types.lua, lua/blink/cmp/sources/lib/utils.lua
The concept of sources groups was copied from nvim-cmp, but in reality, we want to set sources that act as fallbacks for other sources. In the default config, this would be the buffer source acting as a fallback for the LSP source. This avoids the buffer source from never running when using global snippets that always show
Closes #59
=> feat: drop source groups in favor of fallback_for

lua/blink/cmp/accept/text-edits.lua
Rust-analyzer, unlike many other LSPs, returns an empty table instead of nil in additionalTextEdits when it wants to resolve, so we need to check for that too.
For me auto imports and other rust-analyzer edits like `x.some` ->  `Some(x)` were broken but fixed by this.
=> fix: handle empty table in additionalTextEdits

README.md
Name for the snippets source missing in the default configuration in the readme
=> docs: add missing source name in default config

.github/workflows/release.yaml, lua/blink/cmp/fuzzy/download.lua
This PR adds support for pre-built binaries for Windows. Now that #74 is merged, the logical next step is to get this up and running. 
I've set up a separate branch on my fork where actions are enabled and I've tested with a few tags, all looking good on my Windows machine. The binary is downloaded and detected by the plugin just like it is on other OSs:
https://github.com/scottmckendry/blink.cmp/releases/tag/v1.0.3
For obvious reasons, the branch above is different from the one used for this PR 😉 
Resolves #7
=> feat(ci): support windows pre-built binaries

lua/blink/cmp/fuzzy/download.lua, lua/blink/cmp/health.lua
Adds some basic healthchecks that can be run with `:checkhealth`. 
Here is an example of the output of `:checkhealth blink.cmp`:
=> feat: add health.lua and basic healthchecks

lua/blink/cmp/windows/autocomplete.lua
Fixes #109
Escapes newlines in autocomplete to avoid errors.
Now doesn't error (second item has newlines):
=> fix: handle newlines in autocomplete suggestions

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/init.lua, lua/blink/cmp/trigger/completion.lua, lua/blink/cmp/windows/autocomplete.lua
This introduces a new `auto_show` config for the autocompletion menu. It's set to `true` by default, so nothing has changed. If we set it to `false,` then we need to press default or user-set keymaps to show the menu.
=> implement new behavior for autocompletion menu, toggle option to require keypress for showing suggestions.

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/keymap.lua, lua/blink/cmp/trigger/completion.lua, lua/blink/cmp/trigger/signature.lua, lua/blink/cmp/utils.lua
Adds a new config option `ignored_filetypes` that can be used to turn off completions and keymaps for specific filetypes.
It extends the existing `is_special_buffer()` function(now renamed to `is_ignored_buffer` for clarity) to check whether the current buffer's filetype is in the table.
I'm not attached to the implementation. So I'm open to feedback on alternative approaches 🙂 
Resolves #52
=> feat(config): add ignored filetypes option

lua/blink/cmp/windows/signature.lua
I kept getting the following error on main, and this one line change seems to fix it. (Note: I haven't investigated more, so maybe the proper fix is actually to figure out why `signature_help.signatures` can be empty.)
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:822: attempt to index local 'signature' (a nil value)
-- stack traceback:
--         /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:822: in function 'convert_signature_help_to_markdown_lines'
--         .../nvim/lazy/blink.cmp/lua/blink/cmp/windows/signature.lua:39: in function 'open_with_signature_help'
--         .../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:80: in function 'callback'
--         ...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/init.lua:126: …
```
=> Fix signature error

lua/blink/cmp/windows/signature.lua
https://github.com/Saghen/blink.cmp/commit/819b978328b244fc124cfcd74661b2a7f4259f4f#diff-a640c01fb7bc8cf6505b8eb364637612227b1330d4205c09c9fa0d66b5a14072R107
references a `win` that isn't defined, which leads to the following error:
```
Error executing vim.schedule lua callback: .../nvim/lazy/blink.cmp/lua/blink/cmp/windows/signature.lua:107: attempt to index global 'win' (a nil value)
stack traceback:
.../nvim/lazy/blink.cmp/lua/blink/cmp/windows/signature.lua:107: in function 'update_position'
.../nvim/lazy/blink.cmp/lua/blink/cmp/windows/signature.lua:66: in function 'open_with_signature_help'
.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:80: in function 'callback'
...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lib/init.lua:126: in function 'fn' …
```
=> fix: Typo in signature.win

README.md
`blink.cmp` has nice type information, but the current recommended installation script doesn't expose those types to lua-ls. This should help with getting completions from lua-ls.
(Only the first two lines matter. The rest is just automatically removed spaces.)
=> docs: Add LSP type information

lua/blink/cmp/windows/documentation.lua
`cmp_menu` is not a known treesitter parser. Treesitter users get errors when showing the completion docs.
Add "markdown" filetype to `windows.documentation.setup`
=> Fix broken completion documentation

lua/blink/cmp/windows/signature.lua
I had an issue where the signature help window was covering the cursor if there was not enough space above or below the cursor. 
Not sure if this is the correct way to go about fixing it, I think in the future it should have the direction priority like what autocomplete has. I don't know lua though, so best I can do is a temporary solution.
Closes #45
=> fix: signature window no longer overlaps cursor

lua/blink/cmp/config.lua
Hide type warnings when using a table with character highlights:
This is supported by the neovim API, so no other code changes were required 🙂
=> feat(windows): add support for individual border character highlights

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
The repo is large enough that it regularly gets new issues, warranting the use of GitHub issue templates. These can save time for all involved (maintainers & issue creators), since some basic back-and-forth questions, [such as asking whether the user is on a branch or a tag](https://github.com/Saghen/blink.cmp/issues/185#issuecomment-2436210225), could be skipped.
I only added some sensible basics, these can of course be improved later on.
=> chore: add GitHub issue templates

lua/blink/cmp/windows/autocomplete.lua
=> fix: documentation auto show no longer working

lua/blink/cmp/keymap.lua
Bumped into conflicts when trying to use completions from [supermaven](https://github.com/supermaven-inc/supermaven-nvim) (with the `TAB` keymap). Changing blink's keymaps to not be triggered as expressions saved the day — let me know if this is not the intended fix.
_error:_
=> fix(keymaps): expr can't nvim_buf_set_text

lua/blink/cmp/windows/documentation.lua, lua/blink/cmp/windows/lib/docs.lua
Two things in this PR:
- bug fix where signature.win could be `nil`
- don't show the item detail when it's part of the documentation.
=> fix(documentation): better docs

README.md, lua/blink/cmp/keymap.lua
This PR adds the ability to merge a custom keymap with one of the keymap presets.
This is achieved by
1. Extending the `keymap` configuration with a `preset` key which specifies which preset to use
2. Using `vim.tbl_extend` to then merge the preset with the custom keymap
Example:
```lua
keymap = {
preset = 'default',
["<cr>"] = { "select_and_accept", "fallback" },
},
```
=> feat: allow merging of keymap preset with custom keymap

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/windows/autocomplete.lua, lua/blink/cmp/windows/documentation.lua, lua/blink/cmp/windows/lib/init.lua, lua/blink/cmp/windows/signature.lua
This adds the `:h 'winblend'` option to creating windows so we can have psuedo-transparent completion windows.
I think a nice default for the autocompletion winblend config would be `:h 'pumblend'`, but I don't see other options falling back to similar vim options (pumwidth/pumheight) so i've left it at 0.
=> feat: add winblend option for windows

lua/blink/cmp/sources/lib/types.lua
Right now it looks like the code does nil checks perfectly, and there is no actual issue in resolving a nil value. However, the types still specify that a response must always be present.
=> fix(types): allow resolving empty response from blink.cmd.Source

README.md
Add missing BlinkCmpGhostText highlight in README table.
=> feat(docs): add `BlinkCmpGhostText` in highlight groups table

lua/blink/cmp/windows/autocomplete.lua
Just as [labels can return newlines](https://github.com/Saghen/blink.cmp/blob/v0.5.1/lua/blink/cmp/windows/autocomplete.lua#L326-L328), so too can label details.
=> fix: completion label details containing newline characters

lua/blink/cmp/fuzzy/download.lua
Explicitly provide `--git-dir` and `--work-tree` in git commands.
Issue #274
=> fix: download mechanism works with GIT_DIR and GIT_WORK_TREE set

lua/blink/cmp/windows/lib/docs.lua
Add bounds checking to prevent nil indexing when row parameter is outsidethe valid range
Issue #270
=> fix: prevent index out of bounds in get_code_block_range

lua/blink/cmp/windows/lib/scrollbar/geometry.lua
Problem: The scrollbar doesn't touch the bottom of the window when scrolled to the bottom of the list.
Solution: Use the cursorline for positioning the thumb instead of topline
=> fix(scrollbar): use cursorline to determine thumb position

lua/blink/cmp/trigger/completion.lua
The last usage of this function was removed in
https://github.com/Saghen/blink.cmp/commit/7f5a3d9a820125e7da0a1816efaddb84d47a7f18
- fix: always hide window on accept
- (Tue Oct 22 12:23:33 2024 -0400)
=> refactor: remove unused trigger.get_current_word function

flake.nix
building from master fails due to hash mismatch
=> fix: flake hash for frizbee

README.md
Hi! I forked the existing ripgrep plugin after some discussion with its author. So far I have added features like syntax highlighted match previews, unicode support, as well as unit + end to end testing.
https://github.com/mikavilpas/blink-ripgrep.nvim
I wanted to suggest adding it to the readme. Right now it may look a bit confusing in this PR, so let me know if you'd like to have some clarification or something.
=> docs: add blink-ripgrep community plugin to the README

README.md, lua/blink/cmp/config.lua, lua/blink/cmp/utils.lua, lua/blink/cmp/windows/render/column.lua, lua/blink/cmp/windows/render/init.lua, lua/blink/cmp/windows/render/types.lua
If there is a component returning an empty string, the renderer will take it as non-empty and will add a gap:
```lua
windows = {
autocomplete = {
min_width = 1,
draw = {
columns = {
{ "label" },
{ "kind", "label_description", gap = 1 },
},
},
},
}
```
In this case, label_description is empty but the renderer is adding a gap
I have also removed the manual spacing within the `kind` and `kind_icon` components as it should be handled by the gap
=> fix: handle gap for empty text

lua/blink/cmp/windows/signature.lua
Currently, signature help does not highlight the current parameter but always starts from the second character (see image)
By using the right indexes, this gets fixed:
=> fix: signature help now highlights the right parameter

lua/blink/cmp/accept/text-edits.lua
When neovim is v11 or higher, use the new version of str_byteindex like neovim does
Closes #307
=> fix: offset encoding conversion on nvim 0.11.0

README.md, lua/blink/cmp/init.lua, lua/blink/cmp/windows/lib/init.lua, lua/blink/cmp/windows/lib/scrollbar/geometry.lua, lua/blink/cmp/windows/lib/scrollbar/init.lua, lua/blink/cmp/windows/lib/scrollbar/win.lua
- I'm linking documentation and signature help border groups to NormalFloat (similar to the completion menu) as we don't use bordered windows by default. This should be prioritized, resulting in a much better experience with the defaults
=> fix: padded window

lua/blink/cmp/init.lua
Using `Comment` for non text seems a bit confusing inside a comment, I think `NonText` was made for this case
=> fix: default highlight groups

lua/blink/cmp/accept/text-edits.lua, lua/blink/cmp/windows/ghost-text.lua
Fixes #257 
This issue also happens to me in a large Rust project where the LSP is slow. It tries to show a slightly outdated text edit and errors, but shows the correct text edit instantly after. So maybe this could also be fixed with better scheduling.
Now I just make the extmark with pcall to not render outdated ghost-texts and cause errors. Nvim-cmp also does this.
=> fix: make ghost-text extmark with pcall

README.md, lua/blink/cmp/config.lua
Fixes the workflow of copy-pasting the default config.
=> docs: Add missing comma in README

lua/blink/cmp/accept/preview.lua, lua/blink/cmp/utils.lua
Use a modified version of nvim-cmp's word extraction algorithm from expanded snippets for use in auto-insert preview textEdits.
For example, if a snippet expansion results in something like:
```
my_neat_function(int arg1, double arg2)
```
Then the floating window will show the above for that completion, but when selecting it, the buffer will only insert `my_neat_function`. This allows using the snippet completion item without actually _accepting_ it by just selecting it in the preview window and then continuing to type.
So one could type "my_n", Ctrl-N/Tab (or whatever your keymap is) to select `my_neat_function`, and then just continue with typing the ( and args manually. Of course, accepting the completion will still work as expected by expanding the snippet.
=> feat: extract word from completion item for auto-insert preview

.cargo/config.toml, .github/workflows/release.yaml, lua/blink/cmp/fuzzy/download.lua
Resolves #145 
Also includes a refactor of the `system_triple` logic in `download.lua` to make maintaining this a bit easier moving forward. I've abstracted the os/arch definitions into their own table now.
Naturally, I've tested this on Windows, Linux, and Android to make sure this hasn't broken the binary download in any way.
=> feat: add prebuilt binaries for android

README.md
- use lists for things that are lists
- use sublists instead of the non-breaking-space indented paragraphs
- move the default configuration up, since that's the thing most people will regularly come back to
- fix the lspconfig snippet, which was assuming the existence of some variables that aren't there.
- put the `luasnip` section into a `<details>` section. It being the only opened section down there, even though other sections are more relevant makes little sense.
- open the "Community Sources" `<details>` section. There aren't enough there yet to warrant folding them away, and it increases their visibility. Also add a heading to them for navigability, linkability and visibility.
=> docs: simplify various sections

lua/blink/cmp/sources/lib/types.lua
No references to this field are left, so it looks like it was left behind from the issue https://github.com/Saghen/blink.cmp/issues/144
and closed by the commit in that issue,
https://github.com/Saghen/blink.cmp/commit/7fea65c4e4c83d3b194a4d9e4d813204fd9f0ded
=> refactor: remove unused filter_completions from source types

README.md, lua/blink/cmp/completion/windows/render/context.lua, lua/blink/cmp/config/completion/menu.lua, lua/blink/cmp/highlights.lua
allow blink to show source related info in completion menu
example (`LSP` and `Snippets` are item's source_name):
related config from example
```lua
---@module 'blink.cmp'
opts = {
menu = {
draw = {
columns = {
{ "label", "label_description", gap = 1 },
{ "kind_icon", "kind", gap = 1 },
{ "source_name" },
},
},
},
},
},
```
`source_name` has been added as one of default config components for demonstration, but I'm not sure if it's appropriate.
=> feat(render): support `source_id` and `source_name` in menu render

lua/blink/cmp/fuzzy/lib.rs
Issue
=====
When using the "buffer" provider in a buffer with the following contents:
```
työmaa
| <- cursor
```
When typing "ty" the word "työmaa" is not matched, even though it's part of the buffer and should be shown as a suggestion.
> Trivia: työmaa is Finnish and can be translated as "construction site"
> in English. 🙂 The point is to have a word with non-ASCII characters.
Solution
========
Change the regex pattern to match any word character, including unicode characters.
The change allows matching the word "työmaa" when typing "ty" in a buffer.
Considerations
==============
Looking at the Unicode section on rust regular expressions https://docs.rs/regex/latest/regex/#unicode
For maximum performance, it's recommended to stick to ASCII characters when possible. However, I'm using the …
=> feat: allow completing buffer words with unicode

lua/blink/cmp/completion/windows/render/treesitter.lua, lua/blink/cmp/completion/windows/render/types.lua, lua/blink/cmp/config/completion/menu.lua
Quick test of a treesitter highlighter for labels.
Should not be merged yet, since it is currently configured as the default highlighter.
Let me know what you think and if this is something you'd like to have in blink.
Maybe disabled by default and under a config flag somewhere?
=> feat: treesitter highlighter

lua/blink/cmp/sources/buffer.lua
Fixes `failed to get completions with error: blink.cmp/lua/blink/cmp/sources/buffer.lua:19: attempt to index local 'line' (a nil value)`
=> fix: handle nil line

lua/blink/cmp/sources/luasnip.lua
Just a small improvement I noticed
=> refactor(luasnip): use ctx.cursor instead of vim.api.nvim_win_get_cursor(0)

README.md, lua/blink/cmp/highlights.lua, lua/blink/cmp/lib/window/docs.lua
Found highlight group for separator not work, and no description for the highlight group in README.
Not familiar with `nvim_buf_set_extmark`, but it seems work fine.
Before ( separator in doc window should be RED `#9e2e2e` after setting highlight group) :
After (highlight group works)
---
Also I think maybe previous highlight group naming ( `BlinkCmpDocDetail` ) have some ambiguity, therefore currently using `BlinkCmpDocSeparator` as a substitute in the PR.
=> fix(highlight): fix invalid highlight for doc separator

README.md, lua/blink/cmp/lib/window/docs.lua
Some LSP servers like lua_ls would return `---` for function doc, so the manually added separator would make two separator in doc window.
This PR adds some specialized logic to handle this, tested for lua_ls and rust analyzer (lsp server won't return separator), work fine for now.
Before:
- lua_ls (would return `---` for function doc)
- rust analyzer
After:
- lua_ls (would return `---` for function doc)
- rust analyzer (works like before)
=> fix(render): not render two separator for doc window

README.md
Just a minor fix in the docs...
=> docs: fix `enabled_providers` example function, correct typos

lua/blink/cmp/sources/lsp.lua
Seems to be a type error. Should be err instead of error.
Reference: https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/_meta.lua#L5
=> fix: check response.err instead of response.error

lua/blink/cmp/keymap/apply.lua, lua/blink/cmp/keymap/fallback.lua
=> fix(fallback): make fallback work with buffer-local mappings

lua/blink/cmp/completion/windows/documentation.lua, lua/blink/cmp/completion/windows/menu.lua, lua/blink/cmp/lib/window/init.lua, lua/blink/cmp/signature/window.lua
Allow window `filetype` configuration. This makes it easier to prevent other plugins from interfering with blink windows
=> feat(window): add `filetype` configuration

lua/blink/cmp/sources/path/fs.lua
Regression introduced in recent refactoring (#465) where the path
provider was not returning any results.
Ensures that all successfully completed stat operations are returned.
=> fix(provider): restore path completion source

lua/blink/cmp/completion/init.lua, lua/blink/cmp/completion/trigger.lua
Mostly a proof of concept, and probably missing some edge cases. Only prefetches completion responses from sources. Fuzzy still occurs on the first regular trigger, but there is still noticeably less latency.
=> feat(trigger): prefetch on InsertEnter

README.md, lua/blink/cmp/completion/windows/render/types.lua, lua/blink/cmp/config/completion/menu.lua
Closes #438
I'm not sure where exactly to recommend `treesitter = { "lsp" }` in the documentation as was mentioned in the issue. Please also feel free to reword the new description of the `treesitter` field.
=> feat: enable treesiter highlight in menu per source

lua/blink/cmp/config/init.lua
Updated the default `enabled` function so that plugins can disable blink in some buffers.
=> feat(config): allow plugins to disable blink for some buffers

lua/blink/cmp/config/init.lua
Fixes a regression where the completion list was incorrectly enabled in
prompt buffers.
=> fix(completion): disable in prompt buffers

lua/blink/cmp/config/init.lua, lua/blink/cmp/config/types_partial.lua, lua/blink/cmp/init.lua
As mentioned in #427, I added all of the partial config definitions to `config/types_partial`. I didn't create a `Partial` pair for very few of them (e.g. `blink.cmp.KeymapConfig`) because all of their fields are already optional. 
If you want me to change something (split this into multiple files / remove fields' comments / etc. ), let me know.
Edit: these are the types after be3e9cf435588b3ff4de7abcb04ec90c812f1871
=> feat(config): add partial types for each config option

README.md, lua/blink/cmp/sources/luasnip.lua
Luasnip enables to add snippets for all filetypes. These are not added to the completion list. This should be fixed with
this PR.
=> fix(luasnip): Add snippets with ft="all" to completion

lua/blink/cmp/lib/window/scrollbar/win.lua
Closes #580 
There were errors for command-line window cause it's not allowed to delete buffer in command-line window.
At first I want to check if we are in command-line window by checking `getcmdwintype()`, but seems there is no need to always trying to delete buffer for scrollbar thumb and gutter. Cause blink already can reuse existing buffer for scrollbar thumb and gutter.
see below [scrollbar_win:_make_win](https://github.com/Saghen/blink.cmp/blob/76230d5a4a02cd1db8dec33b6eed0b4bc2dcbc53/lua/blink/cmp/lib/window/scrollbar/win.lua#L76C1-L87C4)
```lua
function scrollbar_win:_make_win(geometry, hl_group)
if self.buf == nil or not vim.api.nvim_buf_is_valid(self.buf) then self.buf = vim.api.nvim_create_buf(false, true) end
local win_config = vim.tbl_deep_extend('force', geometry, {
style = …
```
=> not delete buf when hide scrollbar cause it seems not necessary

lua/blink/cmp/sources/path/init.lua, lua/blink/cmp/sources/path/lib.lua
Current the path auto-complete duplicates the `.` character when auto-completing dot files:
https://github.com/user-attachments/assets/528740a4-3f6d-4429-aaec-59a7286215b5
With corrected edit range for files with dot:
https://github.com/user-attachments/assets/0d4f759c-e4d5-419e-9d83-284b6ae24734
=> fix: don't duplicate `.` when completing hidden files in path source

lua/blink/cmp/keymap/init.lua
After debugg my issue [here](https://github.com/Saghen/blink.cmp/discussions/598) I found out that mapping keymaps with lowercase codes (i.e. `<c-space>`, not `<C-space>`) was broken.
The current keymapping logic simply overrides the default preset by overwriting exact matches - in this case, ignoring all my keybindings
(Neo)Vim supports arbitrary capitalization for keymaps (`<Up>`, `<up>`), etc. so I figured blink should too.
=> Normalize Keymap Capitalization

lua/blink/cmp/completion/windows/documentation.lua, lua/blink/cmp/config/completion/list.lua, lua/blink/cmp/config/keymap.lua, lua/blink/cmp/lib/window/docs.lua, lua/blink/cmp/types.lua
This is another attempt at #462 
Issue
=====
The default way of rendering documentation using markdown and treesitter
works great for most cases, but some providers may want to customize the
rendering of the documentation.
However, some providers may want to customize the rendering in order to
add additional information or custom highlighting.
Solution
========
Add a new field `render_documentation_fn` to the `CompletionItem` type.
Providers can set this to a function that will be called when the
documentation is about to be rendered. They can then choose to do custom
rendering or fallback to the default rendering.
Use cases:
- when a treesitter parser is not available for code examples, providers
can display colored text using Neovim's regex based syntax highlighting
- can add additional …
=> feat: allow providers customize documentation rendering

lua/blink/cmp/sources/luasnip.lua
Fixes #662 - Ensure the internal snippet cache is cleared whenever snippets are added or modified. This allows updated snippets to be reflected immediately without requiring a `nvim` restart, addressing the current behavior.
Hey, I think this piece of code fits well in `source.new(opts)`. It works as intended, but if you believe there's a better place for it, let me know, and I’ll make the necessary changes!
Feel free to tell me if I need to make any other changes to this.
=> Clear LuaSnip cache on reload/snippets added

lua/blink/cmp/completion/init.lua, lua/blink/cmp/completion/trigger/context.lua, lua/blink/cmp/completion/trigger/init.lua, lua/blink/cmp/completion/windows/menu.lua, lua/blink/cmp/config/completion/menu.lua, lua/blink/cmp/init.lua, lua/blink/cmp/sources/lsp.lua
This PR gives more control over when and where we show automatic completion. It does this with two public-facing changes:
1. `completion.menu.auto_show` can now be either a function or a constant boolean. This gives users the ability to make more complex decisions about whether to automatically show completions.
2. `blink.cmp.Context` contains a new field -- `update_type`. This field provides additional information on what triggered the update. This allows users to vary behavior when completion is manually triggered (as opposed to being automatically triggered by keywords or trigger characters).
=> feat: improve auto_show flexibility

lua/blink/cmp/completion/windows/menu.lua
This code was reduced by a line before merging PR #697, but it's now hitting the case where the Lua 'ternary' doesn't behave like a proper ternary operator. Specifically, when the `auto_show` function returns false, the result of
```lua
auto_show = type(auto_show) == "function" and auto_show(...) or auto_show
```
becomes
```lua
auto_show = (true and false) or <function>
```
which is the truthy function reference itself.
=> fix: auto_show function logic

docs/recipes.md
The recipe was missing the window, so Blink complains at running. This fix the snippet
=> docs: Add missing window table to set the documentation border

lua/blink/cmp/completion/accept/init.lua, lua/blink/cmp/completion/windows/documentation.lua, lua/blink/cmp/fuzzy/download/init.lua, lua/blink/cmp/init.lua, lua/blink/cmp/sources/cmdline/init.lua, lua/blink/cmp/sources/snippets/utils.lua
Adds the missing title to the notification, which is an informal standard used by notification plugins like `snacks.nvim` or `nvim-notify`. Adding a title is relevant, since without a title it can create confusion which plugin created the notification.
=> fix(notifications): add title to notifications

docs/configuration/reference.md, lua/blink/cmp/config/completion/accept.lua
I think JDTLS already has built in auto-bracket support, but setting this seems to make stuff behave as it should on my part, and [these docs](https://cmp.saghen.dev/configuration/completion.html#auto-brackets) suggested creating a PR.
=> fix: add java to blocked filetypes for semantic token auto_brackets

lua/blink/cmp/fuzzy/init.lua, lua/blink/cmp/sources/buffer.lua
Fixes #725, just makes sure that `package.cpath` is inherited into the worker thread so that user can add their own entries to `package.cpath`.
=> FIX(#725): inherit package.cpath in worker thread

lua/blink/cmp/sources/snippets/registry.lua
Removes some duplication in the snippet loading logic
I was looking into another issue and noticed this one whilst looking through the code base
=> refactor(snippets): simplify snippet loading

.envrc, flake.nix
Hey, please take a look at this proposition of cleaning the flake.nix in this repo:
- kind of unrelated but added a basic .envrc file
- meta, updater scripts etc. are not used outside nixpkgs, can be safely removed (unless you use them in some way?)
- if/else regarding extension can be replaced with a simple glob pattern (tested on linux and darwin)
- removed `rec` and replaced with `self'` - safer
- added inputsFrom to devshell so that we don't need to repeat the same packages and remember about it
As future improvements that build on top of this we could:
- adopt nixfmt-rfc-style https://github.com/Saghen/blink.cmp/pull/736
- make separate src for rust and lua (e.g. now blink-fuzzy-lib compiles every time I change flake.nix or some lua file, it should not be that way)
- find a way to …
=> Refactor and cleanup flake.nix

docs/configuration/sources.md
Hi there,
Adding [blink-emoji.nvim](https://github.com/moyiz/blink-emoji.nvim) to Community Sources.
It is an adaptation of [cmp-emoji](https://github.com/hrsh7th/cmp-emoji/) to better support `blink.cmp`.
Thanks for `blink` :muscle:
=> docs: add blink-emoji.nvim to community sources

docs/configuration/snippets.md
I was unable to disable all of the snippets and kept getting a failure for trying to index into providers. I think the docs might be mistaken here.
=> fix: remove `providers` from transform_items

docs/recipes.md
I find the auto-complete when searching to be distracting and prefer this pattern to maintain the auto-complete when using the command line for commands. Thought it might make a good recipe to include. No biggie if not. 
Thanks for the plugin!
=> docs(recipes): dont show when searching

lua/blink/cmp/init.lua
This is a fix for https://github.com/Saghen/blink.cmp/issues/762: an issue where manually triggering `show()` via a key combo (for those of us that don't use `auto_show`) isn't possible while ghost text is visible.
Note that the current "fix" is very low effort. I simply looked at the definition for `cmp.is_visible()` and decided to just copy one half of that function without the "ghost text is visible part". **This is on purpose! You can interpret this as a _draft_ PR.** I'd be glad to refactor this a bit even if that only means splitting a `cmp.is_menu_visible()` helper function. But...
...I first want to make sure that this fix is desired. I can verify after running this locally that this fixes my issue. But I'm unsure if this breaks anything else.
I'm happy to polish this further, …
=> Allow show() to trigger while ghost-text is visible

flake.nix
This allows to not care about nix files when developing rust.
Cargo hash will be automatically computed from Cargo.lock, while git depencencies will be provided with their checksums by `allowsBuiltinFetchGit` (this is only allowed outside nixpkgs).
=> feat(nix): use Cargo.lock instead of hash

lua/blink/cmp/lib/window/docs.lua, lua/blink/cmp/signature/window.lua
with this change the signature help should show all signatures that are possible given the current parameters.
This is useful for languages that support function overloading.
Given
```cpp
void fn_ov();
void fn_ov(int i, float f, float f2);
void fn_ov(int i, float f);
void fn_ov(int i);
```
it should show:
=> signatures: show all overloads

flake.nix
Allows to be specific about which files should be inputs to which derivation.
The biggest advantages:
- a change in nix file won't trigger plugin nor rust lib rebuild (ofc unless the build function itself changes)
- a change in lua, docs etc. won't trigger rust lib rebuild
Usage is pretty simple, see the comments I've added.
=> feat(nix): use filesets

lua/blink/cmp/completion/windows/documentation.lua, lua/blink/cmp/init.lua
Issue
=====
Providers (completion plugins) can provide a custom implementation for rendering the documentation. Some need to use e.g. Neovim's built-in regex based syntax highlighting. If the documentation window is closed and reopened, the syntax highlighting is lost.
https://github.com/user-attachments/assets/07793221-fc83-49cd-b310-c54c401f562b
Solution
========
Allow plugins to redraw the documentation window when the documentation window is reopened.
https://github.com/user-attachments/assets/7dfe9d62-50a8-4f26-99e3-b73683a1005d
Solves https://github.com/Saghen/blink.cmp/issues/703
=> fix: documentation losing syntax highlighting on doc reopen

lua/blink/cmp/config/keymap.lua, lua/blink/cmp/init.lua
```lua
keymap = {
preset = "super-tab",
["<C-k>"] = {
function(blink_cmp)
if blink_cmp.is_visible() then
blink_cmp.hide()
else
blink_cmp.show()
end
end,
},
},
```
While configuring the key mappings above, I noticed that `blink_cmp` did not provide type annotations, so I add thsi type
=> feat: add type annotation for keymap function params

docs/configuration/sources.md
Hi! I've written a new source for `blink`, this source makes it possible to query word without leaving the editor:
=> doc: add a source for dictionary

lua/blink/cmp/lib/window/init.lua
The current sorting function is not deterministic, because it unfairly prioritizes the first argument. It's not reflexive (I think), which is required for ordering to work correctly.
It sorts the list correctly by accident on Linux, but doesn't on Windows.
I think the intended way is to preserve the original priorities in the case where both have enough space.
Fixes #845
=> fix: fix window direction sorting on Windows

README.md
The old link assumed the section to be in the README.md, but looks like it only exists on the documentation site now.
=> Fix comparison link in README.md

lua/blink/cmp/lib/async.lua
These are just minor improvements. I started to look whether it's possible to implement dot-repeating and came across these while looking.
- silence some lua_ls warnings that came up because the `local task` did not have a type annotation right above it
- make sure all class fields are included
- add @enum for the status field
- silence more warnings by explicitly defining the fields that are used in the class
=> refactor: improve the type annotations to lib/async.lua

lua/blink/cmp/config/keymap.lua, lua/blink/cmp/config/utils.lua, lua/blink/cmp/sources/luasnip.lua, lua/blink/cmp/sources/path/init.lua
this PR replaces vim.validate with it's new 0.11 implementation, that is ~36 000% faster, so it's as fast as no doing no validation at all ( [nvim core PR](https://github.com/neovim/neovim/pull/28977) )
This PR takes codes from an [indent-blankline PR](https://github.com/lukas-reineke/indent-blankline.nvim/pull/934/)
Do not merge this right now, since this is only for 0.11
=> perf: use faster 0.11 vim.validate

flake.nix
I believe there should be some defined formatter, otherwise it's not clear what standards to follow when cotributing to nix files in this repo.
`nixfmt-classic` produces no changes on the current flake.nix.
This is contrary to #736 which introduced a bunch of changes and was rejected.
Use with `nix fmt **/*.nix`
=> feat(nix): add formatter

docs/installation.md, lua/blink/cmp/init.lua, plugin/blink-cmp.lua
See `:help vim.lsp.config` on nightly.
Changing `vim.version` to `vim.fn.has` improved the startup time by about 2-3 ms
=> feat: set default capabilities on 0.11

plugin/blink-cmp.lua
The `plugin/blink-cmp.lua` script added in af1febb17f9ddc87cf73e69d3f61218cdc18ed85 currently doesn't check whether `vim.lsp.config` exists, which causes an error on startup if the Neovim nightly doesn't have this feature (ref. https://github.com/Saghen/blink.cmp/pull/897#issuecomment-2574628478). There is a broad range of development versions of Neovim 0.11 used in the wild, so solely checking for the `nvim-0.11` feature isn't enough.
I considered two alternative implementations for this:
1. _Skip the `vim.fn.has('nvim-0.11')` check entirely since it is not technically required._
-> I left it on purpose because it has the merit of adding explicitness to the script.
1. _Use `pcall().`_
-> Works equally well, but checking for the existence of the function is enough here.
=> Assert that the `vim.lsp.config` function exists before calling it

flake.lock, flake.nix
After https://github.com/NixOS/nixpkgs/pull/352277 when we update nixpkgs in this repo - the plugin build fails with:
```
> Require check failed for the following modules:
>   - repro
```
See: https://github.com/Saghen/blink.cmp/actions/runs/12654863130/job/35263764079?pr=933
Since this file is not needed for any release, we should simply ignore it from nvim sources instead of providing explicit require checks.
What we have here is:
- update flake
- ignore repro.lua from nvimFs (also ignore docs folder because it's quite large and not used at all in vimPlugin)
The "update" step is optional, I just wanted to confirm that the build will fail and that this will fix it. If updating now is not preferred, we can remove that commit.
Note - we could also use `nvimSkipModule` to ignore `repro` but …
=> Fix buildVimPlugin

lua/blink/cmp/signature/trigger.lua
`char` from the `on_char_added` handler, which was used before, doesn't represent the character under the cursor in some situations, such as when using an autopairs plugin.
Fixes #909
=> fix(signature): use `char_under_cursor` in `on_char_added` handler

lua/blink/cmp/completion/windows/ghost_text.lua, lua/blink/cmp/sources/snippets/utils.lua
This pr includes a util function `to_static_text` that correctly transforms
multiline snippets with regards of current line indent. This function is nearly
a copy of `vim.snippet.expand` but without really expanding it, to solely get
the yet-to-inserted text.
before:
after:
=> fix(ghost_text): ensure multiline indent is correct

.github/workflows/spelling.yaml, CHANGELOG.md, _typos.toml, lua/blink/cmp/completion/trigger/init.lua, lua/blink/cmp/sources/cmdline/constants.lua, lua/blink/cmp/sources/snippets/utils.lua
- fix all current typos using [typos-cli](https://github.com/crate-ci/typos)
- add a `_typos.toml`
- add a github action to check pull requests for spelling errors using [typos](https://github.com/crate-ci/typos)
=> feat: spellchecking with typos-cli

docs/configuration/sources.md, lua/blink/cmp/commands.lua, lua/blink/cmp/init.lua
The command `:BlinkCmpStatus` can be used to view which sources providers are enabled or not enabled.
This is inspired by and implemented based on the `:CmpStatus` command from `hrsh7th/nvim-cmp`.
=> feat: add `BlinkCmpStatus` command

.github/workflows/nix.yaml, .github/workflows/release.yaml
Identified with [zizmor](https://woodruffw.github.io/zizmor/). It's also possible to [run zizmore in ci](https://woodruffw.github.io/zizmor/usage/#use-in-github-actions), but I didn't implement this because it requires a GITHUB_TOKEN secret.
=> fix(ci): don't persist credentials in actions/checkout

lua/blink/cmp/sources/cmdline/init.lua
This branch fixes completion issues with commands like `:Rename` in plugins such as [vim-eunuch](https://github.com/tpope/vim-eunuch). You can test it by running `:Rename`, and the completion should work without errors.
The issue was caused by `s:` and `<sid>` functions being scoped to their script, which led to errors like:
> Error while fetching completions: Vim:E120: Using <SID> not in a script context: s:RenameComplete
This fix ensures proper handling of these functions, resolving the issue.
=> fix(cmdline): make completion work for <sid> and s: viml function

lua/blink/cmp/sources/cmdline/init.lua
Should fix cases where a help or file command is prepended with command modifiers (:rightbelow, :vertical, etc.)
i didn't test this much, just did this to fix `:vert h` not returning the complete set of help tags.
=> fix(cmdline): parse for command name if possible

lua/blink/cmp/sources/snippets/default/init.lua, lua/blink/cmp/sources/snippets/default/registry.lua
This can be used with eg.
```lua
filter_snippets = function(ft, file)
return not (string.match(file, "friendly.snippets") and string.match(file, "framework"))
end,
```
to disable friendly-snippets frameworks.
Closes https://github.com/Saghen/blink.cmp/issues/291
Also removes the `ignored_filetypes` option, which is redundant now that users can filter snippets with more control.
=> feat(snippets.default): filter_snippets function for disabling certain snippet files

docs/configuration/keymap.md, lua/blink/cmp/config/keymap.lua, lua/blink/cmp/keymap/presets.lua
The default preset seems to be the only one without the Up/Down keymaps.
This PR adds them.
=> feat(keymap): add Up/Down keymaps to default preset

lua/blink/cmp/sources/cmdline/init.lua
Same fix as #925 but for `v:lua` functions as well.
Found this bug when working on neo-tree, whose completion function is `custom,v:lua.require'neo-tree.command'.complete_args`.
I think v:lua is the only way to call functions on `v:` so it could maybe be shortened to `v:` but up to you.
=> fix(cmdline): make completion work for v:lua functions

docs/installation.md
Changed 'lua-ls' to 'lua_ls' in line 99 so it wont return an error.
=> Typo in Documentation

lua/blink/cmp/config/fuzzy.lua, lua/blink/cmp/config/types_partial.lua, lua/blink/cmp/fuzzy/download/init.lua
The Curl command itself does not use system proxies, so use environment variables to avoid not being able to download the blink libraries in some regions.
=> fix: add proxy for downloading libblink_cmp_fuzzy

lua/blink/cmp/completion/windows/menu.lua, lua/blink/cmp/completion/windows/render/column.lua, lua/blink/cmp/completion/windows/render/init.lua, lua/blink/cmp/completion/windows/render/text.lua, lua/blink/cmp/config/completion/menu.lua
https://github.com/Saghen/blink.cmp/issues/820 may be closed
- `menu.draw.columns` can receive an function with `ctx` args;
- `draw.components._.width.max` can receive an function with `ctx` args (this is needed for set seperate max_width for cmdline);
```lua
menu.draw.columns = function(ctx)
if ctx.mode == "cmdline" then
return { { "kind_icon" }, { "label" } }
else
return { { "kind_icon" }, { "label", "label_description", gap = 1 } }
end
end
draw.components.label.width.max = function(ctx)
return ctx.mode == "cmdline" and 20 or 60
end
```
- docs
- config check should be more detailed.
feel free to change anything to what you want :)
=> feat(menu.draw): columns can be function

lua/blink/cmp/completion/trigger/init.lua, lua/blink/cmp/config/snippets.lua, lua/blink/cmp/init.lua, lua/blink/cmp/lib/buffer_events.lua
Hello @Saghen,
I recently [fixed](https://github.com/hrsh7th/nvim-cmp/pull/2126) this [issue](https://github.com/hrsh7th/nvim-cmp/issues/2119) in `nvim-cmp`.
The problem also occurs in `blink`, and the fix is very similar.
Are there any drawbacks to the following approach?
`.../completion/init.lua`:
```lua
-- trigger -> sources: request completion items from the sources on show
trigger.show_emitter:on(function(event)
vim.schedule(function()
-- schedule to avoid outdated completion items
sources.request_completions(event.context)
end)
end)
```
=> fix: Outdated completion item with mini.snippets

lua/blink/cmp/config/keymap.lua
The `<C-k>` was previously missing in the doc on the `default` keymap which lead to confusion when this keymap was added since it was not shown in the cmp documentation.
=> chore: add <C-k> to default keymap doc

docs/configuration/sources.md, lua/blink/cmp/config/sources.lua, lua/blink/cmp/sources/omni.lua
=> feat: add `omnifunc` completion source

docs/configuration/sources.md
Hi. This adds [blink-cmp-env](https://github.com/bydlw98/blink-cmp-env) to the list of community sources.
=> docs: add `blink-cmp-env` community source

docs/development/lsp-tracker.md, lua/blink/cmp/sources/lib/provider/init.lua, lua/blink/cmp/sources/lsp/init.lua
If the lsp returns commands to run on completion, we now execute them. This is helpful for the Haskell language server which uses commands to implement auto-importing.
=> Apply lsp commands

Cargo.lock, Cargo.toml, lua/blink/cmp/fuzzy/error.rs, lua/blink/cmp/fuzzy/frecency.rs, lua/blink/cmp/fuzzy/keyword.rs, lua/blink/cmp/fuzzy/lib.rs
- remove lazy_static in favor of std LazyLock
- `lib::fuzzy()` only reads the db, so don't acquire a write lock
-  introduce an error type, to avoid including the error descriptions inline. Also decouples fuzzy implementation from mlua.
=> refactor(fuzzy): misc cleanups

lua/blink/cmp/sources/path/init.lua, lua/blink/cmp/sources/path/regex.lua
Fixes #1151 by doing the following:
1. Ensure that `\` is allowed as a trigger character.
2. Fix the path regex to handle Windows correctly.
The implementation for the path regex was taken directly from [async_path](https://codeberg.org/FelipeLema/cmp-async-path/src/branch/main/lua/cmp_async_path/init.lua). I've already tested this on Windows and can confirm that it correctly handles both `C:/` and `C:\` paths.
=> fix: path completion in Windows using backward slash

.github/workflows/docs.yaml
When syncing changes to the forked repository, the deploy-docs job will always run and fail.
With this commit, the deploy-docs job will check if the current github repository is the original "upstream" repository before running the job.
=> ci(docs): do not run deploy-docs job in forks

.github/workflows/stylua.yaml, .stylua.toml, lua/blink-cmp.lua, lua/blink/cmp/config/keymap.lua, lua/blink/cmp/keymap/init.lua, lua/blink/cmp/lib/term_events.lua, lua/blink/cmp/lib/text_edits.lua, lua/blink/cmp/sources/lib/provider/override.lua
This commit fixs formatting in lua files using stylua and updates ".stylua.toml" to use LuaJIT syntax.
A workflow is also added to check whether lua files are formatted using stylua. This workflow runs on pushes to the "main" branch and on pull requests.
=> feat: format lua files using stylua

docs/recipes.md
Addresses #795 by adding recipe to disable command completion in certain scenarios like the following:
disables blink cmp only when running shell commands ( i.e. [ ':!' , ':%!' ] ), but still allows completion in other command modes ( i.e. [ ':' , ':help', '/' , '?' ] etc ).
---
context
on my nvim config running inside windows > wezterm > using git bash shell if i leave cmp on for shell commands nvim hangs as it indexes (i think?) the shell completions. So i put the code from this recipe in my config, thought others might benefit from it aswell!
=> docs(recipes.md): add Disable completion in only shell command mode

lua/blink/cmp/config/keymap.lua
Hey there!
I was thrown of that my languageserver told me my keymappings are wrongly typed, so I took a quick look around and I think the blank line that I removed breaks the typedoc.
At least without it my languageserver is happier than before :D
=> fix(luadoc): KeymapCommand alias broken

lua/blink/cmp/signature/trigger.lua
This is an attempt to fix problem referenced here: 
https://github.com/Saghen/blink.cmp/issues/1071#issuecomment-2628530807
Not sure if this is the right solution though. 
The idea is that if the `config.enabled` is `false` (which is actually `trigger.enabled`) and the signature window is not yet open, exit the logic that processes the trigger.
=> fix: don't always show signature help

docs/configuration/reference.md, lua/blink/cmp/completion/accept/init.lua, lua/blink/cmp/completion/accept/preview.lua, lua/blink/cmp/completion/list.lua, lua/blink/cmp/config/completion/accept.lua, lua/blink/cmp/lib/buffer_events.lua, lua/blink/cmp/lib/term_events.lua, lua/blink/cmp/lib/text_edits.lua, lua/blink/cmp/lib/utils.lua
See #870 for previous work
The main issue atm is with `completion.list.selection.auto_insert = true`, any selected items will be included in the dot repeat, so we should skip the `vim.fn.complete` in that case. If the context changes or we hide, we should then add it to the dot complete. Perhaps we should have a generic "write to dot repeat" function
=> feat: support dot-repeat via `vim.fn.complete`

docs/configuration/completion.md, docs/configuration/keymap.md, docs/configuration/reference.md, docs/configuration/sources.md, lua/blink/cmp/config/completion/documentation.lua, lua/blink/cmp/config/completion/trigger.lua, lua/blink/cmp/config/init.lua, lua/blink/cmp/config/keymap.lua, lua/blink/cmp/config/modes/cmdline.lua, lua/blink/cmp/config/modes/term.lua, lua/blink/cmp/config/modes/types.lua, lua/blink/cmp/config/sources.lua, lua/blink/cmp/config/types_partial.lua, lua/blink/cmp/config/utils.lua, lua/blink/cmp/keymap/init.lua, lua/blink/cmp/sources/lib/init.lua
Moves the `cmdline` and `term` configs to a separate top level `cmdline = {}` and `term = {}`. This should be the last breaking change to the config before 1.0
=> feat!: mode-specific config

lua/blink/cmp/sources/lib/init.lua
Fixes https://github.com/Saghen/blink.cmp/issues/1228
=> fix: check if mode-specific configs are enabled before adding sources

README.md
lsp-tracker link had "docs" instead of "doc", leading to a 404 when clicking
=> typo fix on README.md

.gitignore, doc/configuration/sources.md
Made a tiny completion source for [Conventional Commits](https://www.conventionalcommits.org) types
=> docs(sources): add blink-cmp-conventional-commits to community sources

doc/configuration/reference.md, lua/blink/cmp/completion/windows/ghost_text/init.lua, lua/blink/cmp/completion/windows/ghost_text/utils.lua, lua/blink/cmp/config/completion/ghost_text.lua, lua/blink/cmp/config/init.lua, lua/blink/cmp/config/modes/cmdline.lua, lua/blink/cmp/config/modes/term.lua, lua/blink/cmp/config/modes/types.lua, lua/blink/cmp/lib/cmdline_events.lua
Closes #939
@folke Curious on your thoughts on this, I've used an internal API (`require('noice.ui.cmdline').position`) but the result is quite promising! Perhaps this internal API could be made official? I've started using this with:
```lua
cmdline = {
keymap = { 
['<Tab>'] = { 'accept' },
['<C-Space>'] = { 'show_and_insert' }
},
completion = {
menu = { auto_show = false },
ghost_text = { enabled = true },
},
}
```
=> feat: support ghost text with noice

lua/blink/cmp/completion/windows/menu.lua
=> fix: context not pass to completion.menu.auto_show

lua/blink/cmp/completion/windows/render/init.lua
Setting the decoration provider on every renderer:draw() command caused flickering of incsearch highlights when showing completions for / and ? search modes on the cmdline as characters were typed.
Decoration providers only need to be set once and they remain active, so the fix here is create it when the renderer is created and remember the last bufnr that was drawn to, along with the columns.
Fixes #1061
=> fix: incsearch flickering when typing characters during search

doc/blink-cmp.txt, lua/blink/cmp/config/keymap.lua
Removes the deprecated `keymap.cmdline/term` examples from the `blink.cmp.KeymapConfig` doc comments, and updates them to match the keymap docs on the website.
One note: when I open the hover docs with this change, `require('blink.cmp')[command]()` is rendered incorrectly as  `require('blink.cmp')[command](file:///path/to/blink/cmp/config)` which I assume this is due to a bug in luals.
=> docs: remove deprecated config options from keymap doc comments

lua/blink/cmp/sources/cmdline/init.lua
Fixes a special case where `:=prefix.` is used without a space after the
`=`, which causes the prefix to be discarded when the completion is
accepted.
Closes #1240
=> fix: lua expr cmdline completion clears prior input

flake.nix
see discussion in: https://github.com/Saghen/blink.cmp/pull/1334
Trailing newline caused it to be detected as `{ "tag" = "nix\n" }` instead of `{ "nix" = true } `
=> fix(nix): don't add trailing newline to version

doc/configuration/sources.md
The repo also still contains a source for nvim-cmp, which is why I didn't change the repository name to `blink-cmp-...` like you suggest in the developer documentation. Does this still work for you as a community source?
Thanks for the great plugin! :)
=> docs: add cmp-pandoc-references community source

lua/blink/cmp/config/snippets.lua
Enhances the luasnip integration in the snippets configuration:
- Add support for regex triggers (`regTrig = true`)
- Add support for hidden snippets (`hidden = true`)
- Improve snippet expansion and jumping logic
- Ensure proper handling of expandable snippets
Related discussion: https://github.com/Saghen/blink.cmp/discussions/1245
=> fix: improve luasnip integration and expand functionality

doc/recipes.md
The previous example crashes when the 2 completion item params of the sort function have the same client_name, with:
```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/blink.cmp/lua/blink/cmp/fuzzy/sort.lua:11: invalid order function for sorting
stack traceback:
[C]: in function 'sort'
```
Returning whenever client_names are the same, fixes it.
=> docs: fix recipes fuzzy sorts custom function example

doc/blink-cmp.txt, doc/configuration/reference.md, lua/blink/cmp/config/sources.lua, lua/blink/cmp/sources/complete_func.lua
Currently the `omni` source is a specific implementation of `complete-functions` for omnifuncs only. This PR allows for more control over omnifuncs  (e.g. using two different omnifuncs at once), as well as the creation of sources for any arbitrary complete-func using that machinery.
```lua
-- e.g.
thesaurus = {
name = "Thesaurus",
module = "blink.cmp.sources.complete_func",
opts = {
complete_func = function()
return vim.bo.thesaurusfunc
end,
},
}
```
=> feat!: allow creating generic sources for `complete-functions`

lua/blink/cmp/sources/snippets/luasnip.lua
This addresses an issue where snippets composed only by lua regex
patterns make them barely searchable in the completion menu.
Luasnip provides a `name` property that, when available, display the
snippet's `name` instead of the raw regex `trigger` pattern, making
regex triggers discoverable and user-friendly.
Related to #1373
Co-authored-by: helins <adam@protosens.com>
=> fix: prefer luasnip name over regex trigger in completion results

lua/blink/cmp/lib/window/scrollbar/geometry.lua
Resolves scrollbar rendering issues when LSP servers (e.g., Pyright)
sometimes return blob-type content in documentation. Converts blobs to
strings before computing line widths to ensure accurate documentation
window sizing.
Fix #1320
=> fix: handle blob-type in documentation height computation

lua/blink/cmp/keymap/apply.lua
In addition to insert mode, when an LSP supports snippets for built-in
functions, allow toggling the signature help window in select mode as
well.
=> feat(keymap): toggle signature help window in snippet

lua/blink/cmp/sources/buffer.lua
fixes #1392 
It parses buffers content in chunks which should help to not block the UI thread. I also had to manually dedup words, otherwise we can get duplicates in the completion menu. 
There are definitely ways to improve the performance further. Yet I didn't want to increase the scope of this PR and the option to enforce lua fuzzy implementation already notably highlights that performance won't be as good
=> feat: handle large buf text completion with pure lua

CHANGELOG.md, doc/blink-cmp.txt, doc/configuration/general.md, doc/configuration/reference.md, doc/configuration/sources.md, doc/recipes.md, lua/blink/cmp/config/snippets.lua, lua/blink/cmp/fuzzy/download/git.lua, lua/blink/cmp/fuzzy/rust/error.rs
Hi, I noticed some typos in the documentation, and my autism kicked in, so I went through the entire repo with [hunspell](https://github.com/hunspell/hunspell) 
Great plugin by the way
=> Fix some typos in docs and code

lua/blink/cmp/lib/text_edits.lua
fixes https://github.com/olimorris/codecompanion.nvim/issues/1060
This change preserves the original `buflisted` state of the current buffer when applying LSP text edits. The function `vim.lsp.util.apply_text_edits` forces `buflisted` to true (see https://github.com/neovim/neovim/issues/12488 and https://github.com/neovim/neovim/pull/12489, which is useful for non-current buffers but not desired for the current one. This fix saves the state before applying edits and restores it afterward.
=>  Restore original 'buflisted' state for current buffer

lua/blink/cmp/lib/cmdline_events.lua
Update fallback logic for detecting cursor movements to handle bulk
deletions like `<C-u>` and `<C-w>`.
Fix #1369
=> fix(cmdline): correctly handle bulk deletions in nvim < 0.11

lua/blink/cmp/lib/text_edits.lua
I accidentally added trailing spaces in the [previous PR](https://github.com/Saghen/blink.cmp/pull/1432). Sorry about that 🙂
Now Stylua shows no errors locally.
=> Remove trailing spaces

lua/blink/cmp/sources/lsp/init.lua
Error: "failed to execute item with error: ...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lsp/init.lua:186: attempt to index global 'source' (a nil value)"
=> fix(lsp): missing `source` parameter

lua/blink/cmp/sources/snippets/luasnip.lua
An autosnippet is expanded by Luasnip when its trigger is matched on the
line, skipping the whole blink.cmp `accept` logic.
Solution: Attach a callback to autosnippets that hides the
completion window when 'leaving' the snippet.
Fix #1018
=> fix(luasnip): hide completion window when expanding autosnippets

lua/blink/cmp/sources/snippets/luasnip.lua
The current implementation is
```lua
local range = require('blink.cmp.lib.text_edits').get_from_item(item).range
local clear_region = {
from = { range.start.line, range.start.character },
to = { range['end'].line, range['end'].character },
}
```
However, when expanding autosnippets by `<C-y>`, I find it eat up text after the cursor and when I try to debug it, I find inconsistency in `range['end'].character`, my debug code is
```lua
local range = require('blink.cmp.lib.text_edits').get_from_item(item).range
local clear_region = {
from = { range.start.line, range.start.character },
to = { range['end'].line, range['end'].character },
}
local result = vim.inspect(clear_region)
vim.api.nvim_echo({{result}}, true, {})
```
Video:
[Screencast_20250319_105240.webm](https://github.com/user-attachmen …
=> fix(luasnip): use `cursor` to locate `clear_region.to`

lua/blink/cmp/fuzzy/download/init.lua
The pcall check introduced in commit #38a234e9 loads now the fuzzy rust
lua module. It needs to be cache cleared if required again.
Fix #1471
=> fix(download): handle first-time loading issue of rust lua module

lua/blink/cmp/fuzzy/rust/fuzzy.rs
This may introduce some overhead, but `filter_text` is longer than 512 is rare (`texlab` is the only one I've met),
maybe it is tolerable.
This is only a temporary fix, I hope there will be fuzzy matching for text longer than 512.
close #1473
=> fix(fuzzy): truncate length of `filter_text` to 512

lua/blink/cmp/sources/cmdline/init.lua
=> fix(cmdline): separetely caculate start_pos for `:=xx`

doc/installation.md
tbl_deep_extend() requires two tables passed to it.
=> Doc: Fix typo in installation guide.

doc/configuration/sources.md
Hi. This adds [ecolog.nvim](https://github.com/philosofonusus/ecolog.nvim) to the list of community sources. It allows for completion of environment variables.
=> docs: add ecolog.nvim community source

doc/blink-cmp.txt, doc/configuration/snippets.md
The json in the snippets examples isn't valid because of the trailing space.
=> docs: fix the json in the snippets example

lua/blink/cmp/lib/window/cursor_line.lua
Explicitly stop at the next comma rather than matching everything until
the last comma.
Fix #1513
=> fix(window): correctly extract `CursorLine` winhiglight

doc/recipes.md
Thanks for the great plugin! It feels so much easier and intuitive to customize compared to `nvim-cmp`.
This PR adds a small recipe to exclude short language constants (if, else, while, etc.) from language server autocompletion results. For me, these completions appear after typing just one or two letters, creating unnecessary noise. I've found it's cleaner and simpler to use snippets or manually type these short keywords instead.
Hopefully others find this useful too)
=> docs: add small recipe on how to exclude specific completion type

.github/workflows/docs.yaml
With this commit, an additional check is ran on whether files in 'doc' directory or 'docs.yaml' workflow file are modified.
This prevents documentation website from being updated when there are no changes in documentation nor changes in deployment settings.
=> ci(docs): add path filters to deploy-docs workflow

.luarc.json, lua/blink/cmp/sources/lsp/completion.lua, lua/blink/cmp/sources/lsp/init.lua
Gets rid of the deprecation warnings on nightly Neovim. The approach in this PR is inspired by `fzf-lua`'s implementation: https://github.com/ibhagwan/fzf-lua/blob/caee13203d6143d691710c34f85ad6441fe3f535/lua/fzf-lua/utils.lua#L1374
=> feat: use non-deprecated LSP methods when supported

doc/configuration/sources.md
Hello, I ported, and (slightly extended) the [tmux source for `nvim-cmp`](https://github.com/andersevenrud/cmp-tmux).
=> docs: add blink-cmp-tmux source

lua/blink/cmp/config/snippets.lua
This remove a useless condition to guess if a snippet is in an active
state.
Fix #1553
=> fix(snippet): keep luasnip item in completion list on exact match

doc/blink-cmp.txt, doc/configuration/reference.md, doc/configuration/sources.md, lua/blink/cmp/config/sources.lua
The old description was opposite to the actual meaning.
=> docs: clarify the `async` source provider option

lua/blink/cmp/completion/trigger/context.lua
Correct the comparison logic in `within_query_bounds` by ensuring the
start column check uses `>` instead of `>=`. This resolves an off-by-one
error introduced in commit 60a571e2155c18d18a6021ad4f89709d46e8445a when
converting the cursor column from 0-indexed to 1-indexed.
Fix #1500
Related #1548
=> fix(trigger): adjust query bounds logic to handle 0-indexed cursor

doc/configuration/fuzzy.md, doc/recipes.md
The documentation about custom sorting has been
sparse. This commit adds a link to sorting
in lua and some examples.
=> docs(sorting) Add a few examples to sorting

doc/configuration/reference.md
PR #1030 added proxy support when downloading prebuilt fuzzy binaries.
Adding the changes to the reference Fuzzy docs as well.
=> doc: include proxy settings in Fuzzy reference

lua/blink/cmp/lib/text_edits.lua
Disable Neovide redrawing during dot repeat setup to fix https://github.com/Saghen/blink.cmp/issues/1247
Works in conjunction with https://github.com/neovide/neovide/pull/3097, which will be included in the Neovide 0.15.1 release.
=> fix: disable Neovide drawing when setting up dot repeat

.github/workflows/panvimdoc.yaml
When syncing changes to the forked repository, the panvimdoc workflow will always run when a file in doc directory and/or 'panvimdoc.yaml' workflow file is modified.
This generates an additional "docs: update vimdocs" commit which has to be removed or else it will be included in pull requests.
With this commit, the panvimdoc workflow will check if the current github repository is the original "upstream" repository before running the workflow.
=> ci(panvimdoc): do not run panvimdoc workflow in forks

.github/workflows/stylua.yaml
Before this commit, the stylua workflow only checks lua files in 'lua/' directory.
With this commit, lua files outside 'lua/' directory such as 'repro.lua' and 'plugin/blink-cmp.lua' are also checked by the stylua workflow.
=> ci(stylua): check all lua files

.github/workflows/stylua.yaml
With this commit, an additional check is ran on whether lua files, '.stylua.toml' and 'stylua.yaml' workflow file are modified.
This prevents the stylua workflow from being ran when non-lua, non-stylua config and non-stylua workflow files are updated such as documentation and rust files.
=> ci(stylua): add path filters to stylua workflow

lua/blink/cmp/highlights.lua
Careful!! While testing with themes like [`gruvbox`](https://github.com/search?q=repo%3Aellisonleao%2Fgruvbox.nvim+CmpGhostText&type=code) , [`rose-pine`](https://github.com/search?q=repo%3Arose-pine%2Fneovim+CmpGhostText&type=code), and others, I noticed that the `'CmpGhostText'` highlight group is not defined.  
This causes Neovim to render it as `'Cleared'`, which results in the ghost text appearing as plain white text without any highlight.
To avoid this issue, I’ve updated the highlight to always use `'NonText'`.  
I believe ghost text should appear similar to comments or slightly dimmed, and `'NonText'` generally reflects that intention.
If this behavior isn't desirable or doesn't match your expectations, feel free to close the PR.
=> fix: avoid undefined highlight group 'CmpGhostText'

lua/blink/cmp/completion/accept/preview.lua
In a nutshell, language servers may specify an non-empty textEdit, that doesnt have any content (`newText` == `""` and `range.start` == `range.end`). 
This edge-case was previously unhandled. Now it is.
=> Update preview.lua: Protect against non-empty empty textEdit

doc/blink-cmp.txt, doc/configuration/reference.md, lua/blink/cmp/completion/brackets/config.lua, lua/blink/cmp/config/completion/accept.lua
For `auto_brackets.kind_resolution`, add `cpp` to the `blocked_filetypes` list. This is necessary to ensure appropriate completion behavior, as there are some completion contexts (such as [using-declarations](https://en.cppreference.com/w/cpp/language/using_declaration)) where it is not appropriate to insert parenthesis when completing a function name.
Also, update corresponding documentation to make it consistent with `accept.lua`
=> fix: disable kind_resolution by default for cpp filetype

lua/blink/cmp/config/modes/types.lua, lua/blink/cmp/config/sources.lua, lua/blink/cmp/config/types_partial.lua
the sources type used in the cmdline and term config is not consistent
with that used in the sources config. we unify and correct the types
here since their usage is also unified.
=> fix: unify and correct source list type

doc/configuration/fuzzy.md, lua/blink/cmp/config/utils.lua, lua/blink/cmp/fuzzy/download/init.lua, lua/blink/cmp/init.lua, lua/blink/cmp/lib/utils.lua
The default error message is way too big and it's kinda hard to find the *actual* error part.
Use `nvim_echo()` instead of `error()`.
> As this will most likely be run only once we shouldn't need `notify_once()`.
A few images of the new error is given below,
<sup>Uses `nvim_echo()`</sup>
<sup>Fallback to `vim.notify()` when the other function isn't available</sup>
Ref: #973
=> refactor(validate): Use `nvim_echo` for emitting config errors

lua/blink/cmp/completion/accept/init.lua, lua/blink/cmp/completion/trigger/context.lua
**Summary of the change**
The `set_cursor` function on the `blink.cmp.Context` did not handle terminal mode gracefully. Since terminal buffers support using the `vim.api.nvim_win_set_cursor` function we can just extend the default behavior of `set_cursor` for terminal buffers.
**How I noticed the problem:** 
Every time I've tried to switch to the third (or more) completion entry by hitting my `select_next` keybind in a terminal buffer I ran into this error:
```
Error executing vim.schedule lua callback: ...t/blink.cmp/lua/blink/cmp/completion/trigger/context.lua:106: Unsupported mode for setting cursor: term
stack traceback:
[C]: in function 'assert'
...t/blink.cmp/lua/blink/cmp/completion/trigger/context.lua:106: in function 'set_cursor' …
```
=> fix: Unhandled terminal mode in set_cursor implementation

lua/blink/cmp/sources/path/init.lua, lua/blink/cmp/sources/path/lib.lua
When writing `.gitignore` files (or `.dockerignore` files, etc...), we can prepend the directories to ignore with a forward slash to only ignore the first level directory on a project, e.g.:
```.gitignore
/dist/
```
This will ignore `project_root/dist/`, and won't ignore `project_root/foo/dist/`.
When writing such ignore rules, it is convenient to only autocomplete a list of directories in the current project. This is not possible currently with the `path` source, as using a forward slash autocompletes a list contained at the filesystem root path.
I propose introducing a new option: `ignore_root_slash`, which would always look for directories in the current project, rather than listing directories in the file root path.
=> feat(source/path): ignore root slash

lua/blink/cmp/lib/utils.lua
It seems that the modified bit of code would lead to
```
Error executing vim.schedule lua callback: [...] nvim_echo must not be c
alled in a fast event context
stack traceback:
[C]: in function 'error'
.../.local/share/nvim/lazy/blink.cmp/lua/blink/cmp/init.lua:23: in function 'fn'
vim/_editor.lua:366: in function <vim/_editor.lua:365>
```
and could be suppressed by wrapping it within vim.schedule.
I'm not sure if this is a good idea though.
=> schedule nvim_echo

lua/blink/cmp/config/shared.lua, lua/blink/cmp/lib/window/init.lua, lua/blink/cmp/lib/window/utils.lua
bold style for winborder added in neovim 0.11.1
- https://github.com/neovim/neovim/pull/33221
- https://github.com/neovim/neovim/pull/33189
---
Screenshot of Neovim 0.11.1 + `blink.cmp` completion menu with `bold` style (completion and documentation)
```lua
documentation = {
auto_show = true,
auto_show_delay_ms = 250,
treesitter_highlighting = true,
window = { border = 'bold },
},
completion = {
menu = {
border = 'bold',
}
}
```
=> feat: add bold style for border

lua/blink/cmp/sources/lib/provider/init.lua
When completion is triggered via a trigger character (e.g., `.`), always show the completion menu regardless of the configured keyword length. This aligns with manually-invoked completions and behavior in nvim-cmp.
=> Ignore keyword length on trigger character

lua/blink/cmp/sources/snippets/default/registry.lua
The following error occurred for me now and then, but when it occurred, it occurred regularly, spamming my notifications with it on every keystroke:
```
failed to get completions with error: ....cmp/lua/blink/cmp/sources/snippets/default/registry.lua:144: invalid capture index
```
Upon some investigation, I figured out that this error is dependent on the content of my clipboard: The error only occurs when you have a substring like `%2` in your current clipboard/register.
Due to url-encoding (e.g., `%20` being the encoded space), this is actually quite often the case, especially if you configure the snippet source to use `clipboard_register = "+"`.
Luckily, the fix for this is quite simple, since we just need to escape all `%` for `gsub`.
=> fix(snippets): strings like `%20` in the register resulting in repeated errors

lua/blink/cmp/sources/cmdline/init.lua
Not sure if this is the right fix for this, but it does appear to fix compatibility with Grepper plugin, see this issue here: https://github.com/Saghen/blink.cmp/issues/1512
I don't know much about Lua or the internal workings of this plugin, so unclear if this is the correct fix or not (I.E. if you want to do something better to handle the error, etc).
=> Handle error if getcompletion returns an error

doc/configuration/sources.md
Adds link to erooke/blink-cmp-latex to list of community sources
=> docs: add blink-cmp-latex

flake.lock, flake.nix
update `fenix` input flake and add `rust-jemalloc-sys` to `buildInputs` to support 16k pages (like on asahi linux)
=> nix: fix jemalloc on 16k pages

lua/blink/cmp/lib/utils.lua
We should only set `err` if the notification is an error (follow up to https://github.com/Saghen/blink.cmp/pull/1760#issuecomment-2878734300)
=> fix: only set error notifications to `err` in `nvim_echo`

lua/blink/cmp/lib/text_edits.lua
Fixes https://github.com/olimorris/codecompanion.nvim/issues/1169
Addresses https://github.com/Saghen/blink.cmp/issues/1303#issuecomment-2889569470
=> fix: add dot-repeat hack to terminal mode

doc/configuration/reference.md, lua/blink/cmp/sources/buffer.lua
Add `max_sync_buffer_size` and `max_async_buffer_size` options for
controlling processing mode.
Also refactor buffer source initialization to use unified option table
with basic validation.
Related #1789
=> feat(buffer): add configurable sync/async buffer size thresholds

lua/blink/cmp/completion/brackets/config.lua
Please excuse my terrible commit, I'm still fairly new to neovim, how the plugins work and github in general
By default it's adding brackets after function and cmdlet names for Powershell (which it shouldn't be).  I'm not 100% sure what it uses to determine the language name, but I've found that if I set plugins/blink.cmp.lua like so then it resolves the issue
There are more Powershell file types but I think those are the most popular
```lua
local powershell_types = { "ps1", "ps1m", "ps1d" }
return {
"Saghen/blink.cmp",
opts = {
completion = {
accept = {
auto_brackets = {
kind_resolution = {
enabled = true,
blocked_filetypes = powershell_types,
},
semantic_token_resolution = {
enabled = true,
blocked_filetypes = powershell_types,
},
},
},
},
},
}
```
=> Update config.lua to block auto_brackets for Powershell

doc/configuration/sources.md
Align with neovim upstream's `i_CTRL-X_CTRL-R` now: https://github.com/neovim/neovim/commit/f2373a89d78356423a84e9636d6949b5322ecc69.
=> docs: add `blink-cmp-register` to community sources

lua/blink/cmp/fuzzy/lua/init.lua
guess_keyword_range returns multiple values, but only the first values is used, while the code below expects pair of values.
Fixes: 29c8d7267dd7 ("fix: snippet edit range with lua implementation")
=> fix: put output values of guess_keyword_range into a table

doc/configuration/sources.md
Hi. This adds [blink-cmp-sshconfig](https://github.com/bydlw98/blink-cmp-sshconfig) to the list of community sources.
=> docs: add `blink-cmp-sshconfig` community source

lua/blink/cmp/config/fuzzy.lua, lua/blink/cmp/fuzzy/init.lua, lua/blink/cmp/fuzzy/lua/init.lua, lua/blink/cmp/fuzzy/rust/fuzzy.rs, lua/blink/cmp/fuzzy/rust/lib.rs, lua/blink/cmp/fuzzy/rust/sort.rs, lua/blink/cmp/fuzzy/sort.lua, lua/blink/cmp/fuzzy/types.lua
Moves the sorting to rust when there's no Lua functions provided in the sorting array, which should be the case for 95%+ users. It's possible that we should fallback to the default list of sorts when the number of items is extremely high (10k+) as in the case of tailwind. On my system, this reduced the sorting time from 5ms to 0.8ms on 11k tailwind items
Related to #1752
=> feat: sort in rust when no lua sorts provided

lua/blink/cmp/completion/trigger/init.lua, lua/blink/cmp/lib/buffer_events.lua, lua/blink/cmp/signature/trigger.lua
If one or more blink windows (menu, documentation, or signature) are
visible and the user triggers a different completion menu (like
`omni-complete`, `user-complete`, ...), all blink windows are now
closed automatically.
This prevents the blink menu from staying open on top of the new menu,
making things less confusing for users.
Closes #1806
---
https://github.com/user-attachments/assets/0035b6a8-504c-49c0-bfce-8972e4347a32
---
Same logic used by [nvim-cmp](https://github.com/search?q=repo%3Ahrsh7th%2Fnvim-cmp%20CompleteChanged&type=code) and seems reliable enough.
=> fix(window): hide all blink windows when another completion menu is triggered

lua/blink/cmp/lib/text_edits.lua, lua/blink/cmp/lib/utils.lua
This is a follow-up to #1582. As far as I understand correctly, `nvim__redraw` is necessary to flush the changes to the neovim UI grid, which does not result in an immediate update if rendering is temporarily suspended by Neovide, but in all other types of UI this does result in an immediate redraw, such as when selecting different completion items with CTRL-N/CTRL-P. Compare:
**without my PR:**
https://github.com/user-attachments/assets/951e04c7-312e-4848-8a7d-0046d49a856c
**with this PR:**
https://github.com/user-attachments/assets/52edfc5c-15a2-467e-b18b-9f6d04902412
I was able to notice this because my statusline shows when I am in the popup completion mode (i.e. when `mode(1)` returns `ic`, `ix` or similar), but also, notice that the cursor quickly jumps around in the inserted line. …
=> fix: skip useless redraws when not running in Neovide

Cargo.lock, Cargo.toml, lua/blink/cmp/fuzzy/rust/frecency.rs
- Replace raw CompletionItemKey as database key with a blake3 hash of its bincode serialization in FrecencyTracker.
- Update get_accesses and access methods to use the hashed key.
- Add key_to_hash_bytes helper for consistent key hashing.
- Add blake3 and bincode as dependencies in Cargo.toml.
- Update Cargo.lock to reflect new dependencies.
We replace the raw struct key with a hash to ensure database keys are fixed-size and uniform, which improves storage efficiency and lookup performance. This also avoids issues with variable-length or complex struct keys, and makes the database more robust against future changes to the key's serialization format.
Closes #1905
Closes #1895 
Closes #1832 
Closes #1727
1. I temporary do this synchronously to get and observe the error thrown here …
=> feat(frecency): use blake3 hash as db key for accesses

lua/blink/cmp/sources/cmdline/init.lua
Follow-up to commit 2c3d276b1:
- The range exclusion logic is now stricter and only applies to command completions
- Changed the scope of some helpers to local (private),
- Added more type annotations
- Removed some old, messy logic
=> refactor(cmdline) extract helpers and clarify completion logic

lua/blink/cmp/sources/cmdline/init.lua
Type `:ts xx`, `Error while fetching completions: Vim:E433: No tags file`
=> fix: handle delay on `:ts xx` No tags file error

lua/blink/cmp/sources/cmdline/init.lua
Don't work as expected for me(`!ls` -> `ls`) after dc647b3acd9ffac6fd694d23832f0d85c06a66ca.
=> fix: `!` prefix completion

lua/blink/cmp/sources/cmdline/init.lua
- Option info is now cached on first lookup instead of fetched every time.
- Shortname is shown in the label description for options.
- Fixed accepting option references (like `echo &shiftwidth`) in completions.
=> refactor(cmdline): improve option completion

Cargo.lock, Cargo.toml, lua/blink/cmp/fuzzy/lua/match.lua
Adjusts the scoring in frizbee such that `foo` no longer receives a higher score matched on `f_o_o` than on `fooo`. Adjusts the lua scoring to match frizbee and adds separate gap open/extend penalties to match its behavior. Related: https://github.com/Saghen/blink.cmp/issues/1642#issuecomment-2960907870
=> feat: prefer continuous matches

doc/configuration/reference.md, lua/blink/cmp/config/sources.lua, lua/blink/cmp/sources/cmdline/init.lua
This change makes the previous attempt to disable shell completion in Windows environments more robust:
- Handles both Windows and WSL, instead of only targeting Windows.
- Handles all shellcmd completions, e.g. `:term`, not just the `:!` command.
- Instead of disabling shellcmd completions entirely, temporarily remove system32 from `PATH`. This avoids hangs while still allowing completion items from other locations to be displayed.
Closes #1926
Related #1029
=> fix(cmdline): prevent hangs from shellcmd completion on win32/wsl

lua/blink/cmp/lib/cmdline_events.lua
When pasting text into the command line, we were only looking at the first character (e.g. pasting "vim.treesitter." would just see "v"). 
This happened because we queued up the change on the first key event and ignored the rest, so only the first char got through. Now, we always use the last pasted character, which makes completions work as expected.
Closes #1940
=> fix(cmdline): pick last pasted char for completion, not just the first

lua/blink/cmp/completion/windows/ghost_text/init.lua, lua/blink/cmp/completion/windows/ghost_text/utils.lua
For multiline text edits, LSP's end.character may not always match the cursor column (e.g. rust-analyzer with unmatched parentheses) and could cause out-of-bounds errors when placing ghost text extmarks.
To prevent these errors, use the actual cursor position for ghost text placement.
Related #1197
Closes #1739
=> fix(ghost_text): prevent out-of-bounds on multiline edits

lua/blink/cmp/completion/list.lua, lua/blink/cmp/lib/text_edits.lua
Using the edit's start as the reference keeps the range correct even if completions are refreshed or the cursor moves.
In substance,
The old logic assumes the difference between old and new cursor columns always reflects how much the edit range should move. But if the cursor moves, or if completions are refreshed (trigger char), the "old" cursor column can be completely out of sync with the actual edit range. This can result in negative values (because of the compute of new - old), causing the edit to go backwards or delete the wrong text (end char < start char).
The new logic always computes the offset from the start of the edit range, which I think is stable and always matches the text to be replaced. It only adjusts if the cursor has moved past the original end, expanding the edit to …
=> fix: use edit range start for compensation instead of old cursor

lua/blink/cmp/completion/trigger/context.lua
This extends the completion `context` with the `terminal_command` in terminal buffers as requested in #1747. The `terminal_command` will contain all text starting from the end of the shell prompt to the current cursor position.
Example:
If you type "ls --he" into a terminal buffer in neovim the current line will look something like this:
```
~/Downloads > ls --a| --long
"~/Downloads > " is your prompt <- an extmark is added after this
"ls --a" is the command you typed until your cursor <- this is what will be in `terminal_command`
"|" marks your cursor position
" --long" is dropped because it is after your current cursor position
```
One caveat of this implementation is that it does not support multiline terminal commands. In multiline commands it will always provide you with the content …
=> feat: add terminal_command to the completion context

doc/recipes.md
There is a simple error.
Found when copy pasting from docs.
=> fix(docs): add missing `or`

lua/blink/cmp/keymap/presets.lua
It is my understanding that the `cmdline` keymap preset is meant to replicate the default completion experience in Vim/Neovim. I noticed it is missing a default key for `<End>` which hides the completion for continuing to complete for cases such as paths. This adds it, let me know if it needs anything else! I have also provided recordings of the behavior in a completely clean Neovim instance and then with this change.
Clean, default Neovim: https://asciinema.org/a/tFG3eVlPzhetmShYAIC0akb1I
Same process with this change: https://asciinema.org/a/7CxgstAd4oP8mMPbHRR3CyZMq
_Note:_ One thing to notice in the default Neovim, if the completion only has one item then it doesn't show, this is useful for quickly using `<Tab>` to fill in a deep path with just a single folder. This behavior isn't the …
=> fix(presets): add missing `cmdline` preset to hide completion on `<End>`

doc/configuration/keymap.md, doc/modes/cmdline.md, lua/blink/cmp/config/keymap.lua, lua/blink/cmp/init.lua, lua/blink/cmp/keymap/presets.lua
Add `cmp.select_or_accept()` to select the first candidate if multiple or accept the only candidate.
Update default cmdline keymaps to use it for `<Tab>` and `<S-Tab>`, matching Neovim's cmdline `<Tab>` behavior.
Closes #2032
=> feat: add `select_or_accept` keymap

lua/blink/cmp/completion/windows/render/column.lua
This prevents highlights from overflowing into next columns, ensuring that highlight ranges stay inside their text.
before
after
=> fix(window): clamp highlights to prevent overflow beyond text bounds

lua/blink/cmp/completion/brackets/config.lua
Detect CSS pseudo-class and pseudo-element selectors like `:root`, `::before`, `div:hover` or `div::after` to prevent automatic insertion of brackets in these contexts.
Closes #2052
=> feat(brackets): add css pseudo-class exceptions

doc/recipes.md
This PR implements what is described in the title. I tested it on my Neovim setup, and everything works as expected.
**Context:** I like `lspkind` icons, but I don’t want to rely on `nvim-web-devicons`. With minimal setups becoming more popular, I think this addition would be nice.
=> docs(recipes): Add "mini.icons + lspkind" combination to recipes.md
