Saghen/blink.cmp

- flake.lock
- flake.nix
also fixes typo so it works with nix :)
> chore: update flake inputs

- README.md
> docs: mini.deps installation

- README.md
- lua/blink/cmp/config.lua
- lua/blink/cmp/windows/autocomplete.lua
I named it "minimal" because there is no kind icon, open to change
> feat: add minimal render style

- flake.nix
> fix: binary symlink in flake only working on Linux

- lua/blink/cmp/windows/documentation.lua
Resolves #142 
Adds support for displaying `item.detail` on its own inside the documentation window when `item.documentation` isn't present. 
Not sure if we would want an option for this or not. Open to feedback 🙂
> feat: support detail only in doc window

- flake.nix
> NixOs: resolve frizbee build error

- lua/blink/cmp/sources/lib/context.lua
> fix: only check enabled fallback sources

- lua/blink/cmp/utils.lua
- lua/blink/cmp/windows/autocomplete.lua
Inspiration: https://github.com/NvChad/ui/blob/87578bb7e2bc106127f013f9a1edd7a716f4f6c6/lua/nvchad/cmp/format.lua#L6
> Feature: TailwindCSS highlight supports

- lua/blink/cmp/windows/autocomplete.lua
> feat: align completion window

- lua/blink/cmp/keymap.lua
> fix: allow to be lazy loaded on InsertEnter

- lua/blink/cmp/fuzzy/download.lua
#275 broke the plugin for nix flake users https://github.com/Saghen/blink.cmp/pull/275#issuecomment-2459471104
This should hopefully fix it.
> fix: handle not being in a git repository, fix error on flakes

- lua/blink/cmp/accept/preview.lua
> fix: applying preview text_edit

- .github/workflows/nix-build.yaml
> ci: test nix build on push with linux & macos machines

- README.md
- lua/blink/cmp/sources/snippets/init.lua
> feat(#292): add get_filetype option for snippet source

- README.md
- lua/blink/cmp/lib/utils.lua
- lua/blink/cmp/sources/buffer.lua
~~have open a [conversation](https://github.com/Saghen/blink.cmp/discussions/410) in discussions.~~ which is duplicate of #190.
> feat: support specifies the bufnrs for the buffer source

- README.md
(this is a very cool feature btw)
> docs: treesitter labels are not documented

- lua/blink/cmp/sources/lib/provider/list.lua
- lua/blink/cmp/sources/lsp.lua
also remove the default kind from the LSP source because this is now handled at the sources level
> fix(sources): set default item kind to `Property`

- lua/blink/cmp/sources/luasnip.lua
#603
I was too late and you already fixed it :(
I went about it slightly differently and cache each sub-filetype separately to save some work.
> feat: honor extended luasnip filetypes and cache each

- lua/blink/cmp/lib/utils.lua
> fix: flatten leaves empty tables

- .gitignore
- lua/blink/cmp/completion/brackets/kind.lua
- lua/blink/cmp/completion/brackets/utils.lua
> fix(accept/brackets): respect `item.kind` when moving cursor

- lua/blink/cmp/config/snippets.lua
@Saghen,
This is a quickfix for mini.snippets expand. I missed that one when reviewing your changes...)
> fix(mini.snippets): expand function should have body=snippet

- docs/configuration/reference.md
- lua/blink/cmp/config/signature.lua
- lua/blink/cmp/signature/window.lua
> feat(signature): add `window.show_documentation` option

- docs/configuration/reference.md
- lua/blink/cmp/completion/init.lua
- lua/blink/cmp/completion/windows/ghost_text.lua
- lua/blink/cmp/config/completion/ghost_text.lua
closes https://github.com/Saghen/blink.cmp/issues/552
> feat(ghost_text): show_on_unselected

- docs/configuration/sources.md
This pr is in work.
Those below will be finished in the 'v0.1.0':
The preview:
> doc: add a new source for git completion

- lua/blink/cmp/sources/lsp/init.lua
> fix(lsp): early return on completionItem/resolve

- lua/blink/cmp/fuzzy/download/system.lua
Use `cc -dumpmachine` to attempt to detect the system target triple libc as per https://github.com/Saghen/blink.cmp/issues/160#issuecomment-2630207543
Rather than directly modifying the system C compiler's target triple and using that, grab the libc portion only. This is to ensure there's no weirdness with some system not doing exactly as expected.
If you want to just directly use the target triple as in #160 above, let me know.
> feat: automatic runtime linux libc detection

- doc/blink-cmp.txt
- doc/configuration/reference.md
Adds the proper documentation for the omni source.
> docs: add omni source to the providers list

- lua/blink/cmp/sources/lsp/init.lua
Fixes https://github.com/Saghen/blink.cmp/issues/1219
Tested in both neovim versions
> fix: trigger custom client LSP commands

- doc/development/source-boilerplate.md
- doc/development/writing-sources.md
- doc/vimdoc.md
Adds a boilerplate for creating sources, and will eventually include a guide on how to write them
> docs: developing sources

- flake.nix
After 2dbc1b78cda0632029d946b709eddaf43d9b13e0 we can disable this
> feat(nix): remove unneeded fetchGit

- lua/blink/cmp/sources/cmdline/init.lua
This ensures that boolean options are correctly listed with both their
truthy and falsy forms, eg `cursorline` and `nocursorline`.
This also correctly handle file and directory completion names using
`:find` and other related commands. See :h 'path'.
Fix #1366
> fix(cmdline): handle boolean options and improve file completion

- lua/blink/cmp/fuzzy/download/init.lua
> FIX(#1410): fallback check if frizzbee shared library exists, if all else fails

- lua/blink/cmp/sources/snippets/luasnip.lua
Improves readability of expanded luasnip regex trigger by using
`docTrig` as a placeholder (when available) instead of the less
intuitive regex pattern.
For example, if the user opts in, expanding a snippet with the trigger
`(%d%d%d%d)(%d%d)(%d%d)` would insert `20250303` rather than the regex
itself. The ghost text will also reflect this change.
Fix #1373
> feat(snippet): add opt-in `prefer_doc_trig` for luasnip regex trigger

- doc/configuration/sources.md
I made a supermaven compatibility plugin since I was having issues with it. I'm not sure if it's working 100%, but if anyone can test too and give me feedback too.
Plugin source: https://github.com/Huijiro/blink-cmp-supermaven
> doc: updated community sources

- lua/blink/cmp/completion/windows/menu.lua
> fix: menu position for multibyte characters

- doc/configuration/sources.md
This PR adds a line that links to the gitmoji project
> Add gitmoji to community sources

- lua/blink/cmp/completion/windows/ghost_text/init.lua
fixes #1648 
Not sure if it's the suitable way to do it.
> fix: ghost_text preview error on completion cancellation at buffer end

- doc/configuration/sources.md
Adding a new source for `package.json` files 🙂
https://github.com/alexandre-abrioux/blink-cmp-npm.nvim
> docs: add blink-cmp-npm

- lua/blink/cmp/sources/buffer.lua
> fix(buffer): deduplicate words globally

- doc/configuration/reference.md
- lua/blink/cmp/config/sources.lua
- lua/blink/cmp/sources/lsp/completion.lua
- lua/blink/cmp/sources/lsp/hacks/lua_ls.lua
> fix(lsp): filter out text completion items only for lua_ls

- doc/configuration/keymap.md
- doc/modes/cmdline.md
- lua/blink/cmp/config/keymap.lua
- lua/blink/cmp/keymap/presets.lua
> feat(keymap): add fallback action to <C-e> mapping

- doc/configuration/sources.md
Fast, offline word source, using Double-Array Trie data structure to achieve faster query speeds.
https://github.com/xieyonn/blink-cmp-dat-word
> docs(source): Add source blink-cmp-dat-word
